---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lunch
  namespace: flux-system
spec:
  chart:
    spec:
      chart: 12factor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: lalyos
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: lalyos
  values:
    color: hotpink
    title: Lunchtime for lalyos
